// app/layout.tsx
import './globals.css';
import React from 'react';
import AuthWrapper from '@/components/AuthWrapper';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log('✅ RootLayout mounted (server)');

  return (
    <html lang="en">
      <body>
        <AuthWrapper>
          {children}
        </AuthWrapper>
      </body>
    </html>
  );
}